language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-ngbp-ui' ]; then cd .. && eval "mv $currentfolder generator-ngbp-ui" && cd generator-ngbp-ui; fi

